#!/bin/sh

set -e

# ----------------------------------------------------------------------------------------

# Parse parameters
while [ $# -gt 0 ]
do
  case "${1}" in
    -H|--host) shift
      HOST="${1}"       ;;
  esac
shift
done

/usr/sbin/fping "${HOST}"

exit $?
