#! /bin/sh

PROGARGS="daemon -c /etc/icinga2/icinga2.conf -e /var/log/icinga2/error.log"
PROGHOME="/usr/lib/icinga2"
PROGNAME="/usr/sbin/icinga2"

## HACK - s6 doesn't handle forking well (at all?)
## Kill the service after a reload to allow s6 to take over.
/bin/sleep 1
/usr/bin/killall icinga2 2> /dev/null
##

exec ${PROGNAME} ${PROGARGS}
