---
version: '3.3'

services:

  consul:
    image: bodsch/docker-consul
    container_name: consul
    hostname: consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
      - 53:53
    environment:
      - CONSUL_UI_BETA=true
    command: 'agent -data-dir /data -server -bootstrap-expect 1 -ui -client=0.0.0.0'
    networks:
      - backend
