---
version: '3.3'

services:
  # the Icinga2 Master
  # includes a certificate service to create and provide a icinga certificate
  icinga2-master:
    build:
      context: ..
      dockerfile: Dockerfile.master
      args:
        - BUILD_DATE=${BUILD_DATE}
        - BUILD_VERSION=${BUILD_VERSION}
        - ICINGA2_VERSION=${ICINGA2_VERSION}
        - CERT_SERVICE_TYPE=stable
        - CERT_SERVICE_VERSION=0.18.3
    container_name: icinga2-master
    hostname: icinga2-master.matrix.lan
    restart: always
    privileged: false
    ports:
      - 5665:5665
      - 8080:8080
    environment:
      - CONFIG_BACKEND_SERVER=consul
      - CONFIG_BACKEND=consul
      - ICINGA2_API_USERS=root:icinga,dashing:dashing,cert:foo-bar
      - DEBUG=0
      - LOG_LEVEL=INFO
      - MYSQL_HOST=database
      - MYSQL_ROOT_USER=${DATABASE_SYSTEM_USER}
      - MYSQL_ROOT_PASS=${DATABASE_ROOT_PASSWORD}
      - IDO_PASSWORD=${IDO_PASSWORD}
      # environment variables for the certificates service
      - ICINGA2_MASTER=icinga2-master.matrix.lan
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PASS=admin
      - CERT_SERVICE_BA_USER=admin
      - CERT_SERVICE_BA_PASSWORD=admin
      - CERT_SERVICE_API_USER=root
      - CERT_SERVICE_API_PASSWORD=icinga
      - CERT_SERVICE_SERVER=nginx
      - CERT_SERVICE_PORT=443
      - CERT_SERVICE_PATH=/cert-service/
      - CARBON_HOST=
      - CARBON_PORT=2003
      - DEMO_DATA=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - database
    networks:
      - database
      - backend

