#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

cat << EOF > .env
BUILD_IMAGE=${BUILD_IMAGE}
BUILD_DATE=${BUILD_DATE}
BUILD_VERSION=${BUILD_VERSION}
ICINGA2_VERSION=$(./hooks/latest-version.sh)

CERT_SERVICE_TYPE=${CERT_SERVICE_TYPE}
CERT_SERVICE_VERSION=${CERT_SERVICE_VERSION}

# prints some debug information of the configurations scripts
# 0 = off, 1 = on
DEBUG=0

# stop the configuration scripts
# 0 = off, 1 = on
DEVELOPMENT_MODUS=0

# for the icinga-cert-service
# info, notice, warning, debug
LOG_LEVEL=notice

# notice, debug, warning, critical
ICINGA2_LOGLEVEL=critical

ICINGA2_MASTER=icinga2-master.matrix.lan
ICINGA2_PARENT=icinga2-master.matrix.lan

DEMO_DATA=false

# graphite support
# CARBON_HOST=graphite.matrix.lan
# CARBON_PORT=2003

# influx
INFLUXDB_DB=icinga2
INFLUXDB_HTTP_AUTH_ENABLED=true
INFLUXDB_ADMIN_USER=admin
INFLUXDB_ADMIN_PASSWORD=hqkBGSQW34iDRpbU
INFLUXDB_USER=icinga2
INFLUXDB_USER_PASSWORD=w7uK6nfcxR6ZBtZC

# influx integration
INFLUXDB_HOST=influx.matrix.lan
INFLUXDB_PASS=w7uK6nfcxR6ZBtZC


# grafana
URL_PATH=/grafana
# LOG_LEVEL=info
ROUTER_LOGGING=false

GRAFANA_HOST=grafana
GRAFANA_PORT=3000
GRAFANA_AUTHENTICATION=token
GRAFANA_TOKEN=
GRAFANA_ENABLE_LINK=yes
GRAFANA_SHOW_DEBUG=0
GRAFANA_PUBLIC=yes
GRAFANA_PUBLIC_HOST=localhost/grafana
GRAFANA_PUBLIC_PROTOCOL=https
GRAFANA_THEME=light

GRAFANA_DASHBOARD_UID=icinga2-default

GRAFANA_PUBLIC_HTTP_PATH=/grafana


# mariadb
MARIADB_SYSTEM_USER=root
MARIADB_ROOT_PASSWORD=vYUQ14SGVrJRi69PsujC
MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
IDO_PASSWORD=qUVuLTk9oEDUV0A

BASIC_AUTH_PASS=admin
BASIC_AUTH_USER=admin

CERT_SERVICE_BA_USER=admin
CERT_SERVICE_BA_PASSWORD=admin
CERT_SERVICE_API_USER=root
CERT_SERVICE_API_PASSWORD=icinga
CERT_SERVICE_SERVER=nginx.matrix.lan
CERT_SERVICE_PORT=443
CERT_SERVICE_PATH=/cert-service/

TICKET_SALT=4QFITXxpOJXtQwuQXhD6oclZ3UPGVGT20s4s28uV

EOF

docker-compose \
  --file compose/head.yml \
  --file compose/database.yml \
  --file compose/nginx.yml \
  --file compose/master.yml \
  --file compose/satellite.yml \
  config > docker-compose.yml

#  --file compose/icingaweb2.yml \
#  --file compose/influxdb.yml \
#  --file compose/grafana.yml \
