#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

cat << EOF > .env
BUILD_IMAGE=${BUILD_IMAGE}
BUILD_DATE=${BUILD_DATE}
BUILD_VERSION=${BUILD_VERSION}
ICINGA2_VERSION=${ICINGA2_VERSION}

LOG_LEVEL=DEBUG

ICINGA2_LOGLEVEL=critical
ICINGA2_MASTER=icinga2-master.matrix.lan
ICINGA2_PARENT=icinga2-master.matrix.lan

DEMO_DATA=false

CARBON_HOST=
CARBON_PORT=2003

MARIADB_SYSTEM_USER=root
MARIADB_ROOT_PASSWORD=vYUQ14SGVrJRi69PsujC
MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
IDO_PASSWORD=qUVuLTk9oEDUV0A

BASIC_AUTH_PASS=admin
BASIC_AUTH_USER=admin

CERT_SERVICE_BA_USER=admin
CERT_SERVICE_BA_PASSWORD=admin
CERT_SERVICE_API_USER=root
CERT_SERVICE_API_PASSWORD=icinga
CERT_SERVICE_SERVER=nginx
CERT_SERVICE_PORT=443
CERT_SERVICE_PATH=/cert-service/

TICKET_SALT=4QFITXxpOJXtQwuQXhD6oclZ3UPGVGT20s4s28uV

EOF

docker-compose \
  --file compose/head.yml \
  --file compose/nginx.yml \
  --file compose/database.yml \
  --file compose/icingaweb2.yml \
  --file compose/master.yml \
  --file compose/satellite.yml \
  config > docker-compose.yml
