#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

docker run \
  --rm \
  --name ${DOCKER_NAME_SPACE}-${DOCKER_IMAGE_NAME} \
  --hostname ${DOCKER_NAME_SPACE}-${DOCKER_IMAGE_NAME} \
  --privileged \
  ${PORTS} \
  ${VOLUMES} \
  ${ENV} \
  ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:${DOCKER_VERSION}
