#!/bin/bash

set -x

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

docker stop \
  ${DOCKER_NAME_SPACE}-${DOCKER_IMAGE_NAME}
